version: '3'

services:
   app:
      build:
         context: .
         dockerfile: Dockerfile
      volumes:
         - '.:/app'
         - /app/node_modules
      container_name: sound-scape-frontend
      ports:
         - 5173:5173
